name: dino-park-fence
rev: latest
aws_region: us-west-2
internal_updates: false
dinopark_fence_replicas: 1
ingress_replicas: 1
oidc_replicas: 1
router_replicas: 1
gatekeeper_replicas: 1
env_dino_park__orgchart__related_endpoint: "http://dino-park-tree-service:80/orgchart/related/"
env_dino_park__orgchart__trace_endpoint: "http://dino-park-tree-service:80/orgchart/trace/"
env_dino_park__orgchart__full_endpoint: "http://dino-park-tree-service:80/orgchart"
env_dino_park__search__simple_endpoint: "http://dino-park-search-service:80/search/simple/"
env_dino_park__fossil__upload_endpoint: "http://dino-park-fossil-service:80/avatar/send/"
env_dino_park__lookout__internal_update_enabled: "true"
env_dino_park__lookout__internal_update_endpoint: "http://dino-park-lookout-service:80/internal/update"
public: false