---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: oidc-proxy
  name: oidc-proxy
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.oidc_replicas }}
  template:
    metadata:
      labels:
        name: oidc-proxy
    spec:
      containers:
        - image: {{ .Values.docker_registry }}/mozilla.oidc.accessproxy:berlin
          imagePullPolicy: Always
          name: oidc-proxy
          ports:
            - containerPort: 80
          env:
            - name: client_id
              valueFrom:
                secretKeyRef:
                  name: oidc-proxy-secret
                  key: client_id
            - name: client_secret
              valueFrom:
                secretKeyRef:
                  name: oidc-proxy-secret
                  key: client_secret
            - name: discovery_url
              valueFrom:
                secretKeyRef:
                  name: oidc-proxy-secret
                  key: discovery_url
            - name: discovery_url
              valueFrom:
                secretKeyRef:
                  name: oidc-proxy-secret
                  key: discovery_url
            - name: backend
              valueFrom:
                secretKeyRef:
                  name: oidc-proxy-secret
                  key: backend
            {{- if ne .Values.env "dev" }}
            - name: allowed_group
              valueFrom:
                secretKeyRef:
                  name: oidc-proxy-secret
                  key: allowed_group
            {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    name: oidc-proxy
  name: oidc-proxy
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    name: oidc-proxy
